# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/lab12/FPGALab-RISC-V-CPU-design/lab12.srcs/sources_1/ip/text_mem/text_mem.xci
# IP: The module: 'text_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/lab12/FPGALab-RISC-V-CPU-design/lab12.gen/sources_1/ip/text_mem/text_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'text_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Project/lab12/FPGALab-RISC-V-CPU-design/lab12.srcs/sources_1/ip/text_mem/text_mem.xci
# IP: The module: 'text_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/lab12/FPGALab-RISC-V-CPU-design/lab12.gen/sources_1/ip/text_mem/text_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'text_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
